### PR TITLE
Refactor DiscoverPort to procedural awaitable code

### LINKED ISSUE #148: Re-implement DiscoverPorts based on a request/response architecture
Currently the DiscoverPorts works in an event style programming matters. It fires many port discovery requests and awaits their responses. While this might have some performance benefits, with fast adapters it might overload the hub.

A better architecture is a request / response pair.

See conversation around #145

### PR DESCRIPTION
**Pull request by tthiery**
- Removed event driven message counting and promise checking
- Loop through messages and await all messages
- Should prevent that different BLE stacks overload the hubs (or stack)

Closes #148 non-breaking

### CODE REVIEW

**Comment by tthiery** [comment]
@dkurok Can you review and test this with your implementation? c&p the discoveryport.cs should work

**Comment by tthiery** [comment]
Code Quality improved significantly (readability wise)

**Comment by dkurok** [comment]
@tthiery I tried the new version of DiscoverPorts.cs with the BlueGiga-adapter.
With Technic-Medium Hub and 3 attached motors and the 88007 colorDistance-sensor (VisionSensor 0x0025) it takes 30 to 35 seconds. TwoPortHub with one motor and 88007 <20secs. No hanging, no waiting, perfect!
Just one question:
Any reason why you store the result of _protocol.SendMessageReceiveResultAsync in variables in RequestPortProperties() whereas in RequestPortModePropertiesAsync() you're giving them directly into KnowledgeManager.ApplyStaticProtocolKnowledge(...)?

But again: This works perfectly now with BlueGiga-adapter!

**Comment by tthiery** [comment]
No specific reason. I thought I would need the messages more. And for the later, i just did not want to create seven meaningless variables.

**Pull request merged**
