### PR TITLE
Add Color&Distance Sensor (#88007) as a Device 

### LINKED ISSUE #103: Add Color&Distance Sensor (#88007) as a Device

### PR DESCRIPTION
**Pull request by highstreeto**
This adds the Color&Distance Sensor as `ColorDistanceSensor`.

The following outputs are implemented currently:
- Color
- RGB
- Proximity
- Refelction
- AmbientLight
- Count (? not sure what this exactly does, seems to react to gestures)

Closes #103 non-breaking

### CODE REVIEW

**Comment by tthiery** [comment]
I had an initial pass over the contribution. Looks good so far. Tell me when you are done, then I can review and merge it.

I will have a breaking v4.0 (on .NET 5) version within the next month. Is that early enough for you?

**Comment by tthiery** [comment]
Oh, and please also update the README.md ... that is always a nice closure ;)

**Comment by highstreeto** [comment]
> 
> 
> I had an initial pass over the contribution. Looks good so far. Tell me when you are done, then I can review and merge it.
> 
> I will have a breaking v4.0 (on .NET 5) version within the next month. Is that early enough for you?

I am not in a rush (as I can use my fork in the meantime), so early or late April works for me.

> 
> 
> Oh, and please also update the README.md ... that is always a nice closure ;)

Done

**Comment by tthiery** [comment]
Are you done with the contribution? In that case I would merge it.

**Comment by highstreeto** [comment]
> 
> 
> Are you done with the contribution? In that case I would merge it.

So now should be done, I changed the deltaInterval for color and count to 1 (which makes more sense)

**Comment by tthiery** [comment]
I just saw a commit message which stated you have not tested with real hardware: Have you by now?

**Comment by highstreeto** [comment]
> 
> 
> I just saw a commit message which stated you have not tested with real hardware: Have you by now?
> 
> I was squashing already ;)

Ah, I tested with the real sensor since the 'Add test for ColorDist. sensor ' commit.
I wrote this in my first commit, as I had to wire up to infrastructure code to handle the Color&Dist. sensor

**Pull request merged**
