### PR TITLE
Added new static port information for TechnicLargeLinearMotor

### LINKED ISSUE #193: poweredup device list hangs
As mentioned in the other thread, I think this is a separate problem, so will make it's own ticket. 

The commandline tool hangs on receiving messages, for instance when running `poweredup device list`. It does work when I detach all my motors. 

My configuration is mentioned [here](https://github.com/sharpbrick/powered-up/issues/58#issuecomment-1874470180)

Tried with the latest release, as well as the latest main. 

When I enable debugging I get the following output (a few of the log messages are mine):

```
Scan Started. Please select the Hub (using a number keys or 'q' to terminate):
1: TechnicMediumHub (with address 90:84:2B:63:D2:B5)
1
Selected TechnicMediumHub with key 1
Discover Ports. Receiving Messages ...
info: SharpBrick.PoweredUp.Protocol.LegoWirelessProtocol[0]
      Connected to device, getting protocol information
Discovering ports.
info: SharpBrick.PoweredUp.Functions.DiscoverPorts[0]
      Number of Ports announced: 13
info: SharpBrick.PoweredUp.Functions.DiscoverPorts[0]
      Discover Port 0-0
..info: SharpBrick.PoweredUp.Functions.DiscoverPorts[0]
      Discover Mode 0-0-0
.......info: SharpBrick.PoweredUp.Functions.DiscoverPorts[0]
      Discover Mode 0-0-1
.......info: SharpBrick.PoweredUp.Functions.DiscoverPorts[0]
      Discover Mode 0-0-2
.......info: SharpBrick.PoweredUp.Functions.DiscoverPorts[0]
      Discover Mode 0-0-3
.......info: SharpBrick.PoweredUp.Functions.DiscoverPorts[0]
      Discover Mode 0-0-4
.......info: SharpBrick.PoweredUp.Functions.DiscoverPorts[0]
      Discover Mode 0-0-5
.
```

### PR DESCRIPTION
**Pull request by mennolodder**
This is the last issue to fix #193

### CODE REVIEW

**Comment by tthiery** [comment]
Hi @mennolodder 

for this I need some time. I need to see how my unpatched motors/hubs react and maybe even update my motor/hub. The XLarge motors are basically twins to the Large ones so I expect the same behavior there.

**Comment by tthiery** [comment]
So I re-run discovery on my xlarge and linear motors. Unfortunately, both are still reporting as `0.0.0.1000`. So the new (yours) and old (mine) output is not distinguishable.

**Comment by tthiery** [comment]
So the change in your PR is compatible with the unpatched motor (which is good, then we can merge it without harm).

The hex-code contain two details
- The self-description raw range is changed from -360 to +360 to -179 to +180 which reflects also the real values we get (so they fixed the description to the actual behavior).
- The removed the ["CALIB" mode](https://github.com/sharpbrick/docs/blob/master/devices/techniclargelinearmotor.md) ... which is probably a calibration mode during production or development of the motors (something like a final qualification test for the motors)

**Comment by tthiery** [comment]
I was able to use the Technical Control+ App to trigger a firmware update on my technic hub. Which allowed me to add the XLarge motor as well.

**Comment by tthiery** [comment]
Had to fix the Robot Inventor `TechnicMediumAngularMotorGrey` as well (tons of updates there). The sensors (distance and color) still worked. Unfortunately, this leaves `TechnicLargeAngularMotorGrey` hanging in the air (I do not have this one).

@rickjansen-dev I think you originally contributed this motor any chance you can update your firmware (e.g. via Technic Control+ app) and provide us updated hex-dumps and pretty prints?

**Comment by tthiery** [comment]
@mennolodder Thanks for your work and patience here. I was a bit under stress work-wise and unfortunately could not have a look earlier.

Unfortunately, the change was indeed a bit worse than expected. But I think both your fixes, the discovery disablement and this one will improve this product a lot. I would love to give @rickjansen-dev some days to respond. My goal is that at the end of the week to release v5.0.

**Comment by mennolodder** [comment]
Sweet, no problem. Glad I could help

**Pull request merged**
